version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    image: ${APP_NAME}:dev
    container_name: ${APP_NAME}-dev
    volumes:
      - .:/code
    command:
      - python
      - /code/app/main.py
