#!/bin/bash

set -e

GREEN="\e[32m"
ORANGE="\e[33m"
NC="\e[0m"

echo "${GREEN}=> Building image. It can take several minutes...${NC}"
echo "${ORANGE}   running: docker-compose build -q${NC}"
echo ""
docker-compose build -q

echo "${GREEN}=> Edit code locally and use 'sh scripts/run' command${NC}"
echo "${GREEN}   to execute the main script in the container${NC}"
echo ""
