#!/bin/bash

set -e

GREEN="\e[32m"
ORANGE="\e[33m"
NC="\e[0m"

echo "${GREEN}=> Running snail game${NC}"
echo "${ORANGE}   running: docker-compose run --rm dev${NC}"
echo ""
docker-compose run --rm dev
